# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 3 # pagination based on number of posts
paginate_path: "page:num"
exclude: [vendor] # files to exclude
highlighter: rouge
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Recent Posts

description: Quang Vo's Website and Blog
author:
  name: Quang Vo
  email: quang.vo31@gmail.com
  github: newsn31
  twitter:
  pinterest:
  linkedin: quang-vo/b1/880/94
  sitedescription: Hi, welcome to my blog that I never update!
  bio: An aspiring software engineer.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
