# Site settings
title: Newsn Blog
email: quang.vo31@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /blog/ # the subpath of your site, e.g. /blog/
url: http://newsn31.github.io/ # the base hostname & protocol for your site
github_username:  newsn31

# Build settings
# Build settings
highlighter: true
markdown: kramdown
permalink: pretty